// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqsBvmet277gCuvxDCBD9cQECrU0eWJ7U',
    appId: '1:870662297667:web:adc76f1996302488c05cf6',
    messagingSenderId: '870662297667',
    projectId: 'sound-s-cool',
    authDomain: 'sound-s-cool.firebaseapp.com',
    storageBucket: 'sound-s-cool.firebasestorage.app',
    measurementId: 'G-5HRRHBG894',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC76zaak53CuaZVRoSl2FZzlygnhE3fmxQ',
    appId: '1:870662297667:android:d600c9426d30d98dc05cf6',
    messagingSenderId: '870662297667',
    projectId: 'sound-s-cool',
    storageBucket: 'sound-s-cool.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEYUlRFlWupALbsdWxfCIXsQyis2fUJLM',
    appId: '1:870662297667:ios:bf86afb2d6c11477c05cf6',
    messagingSenderId: '870662297667',
    projectId: 'sound-s-cool',
    storageBucket: 'sound-s-cool.firebasestorage.app',
    iosBundleId: 'com.example.soundsCool',
  );
}
